### ISSUE TITLE
Binary not found in DB

### ISSUE THREAD

**Issue by Tstan0** [ProjectSerotonin/vlfx#1]
Hello, i am using vlfx whith FwClubSportBaseUpdater.exe but i see this message "Binary not found in DB".

Could you send the firmware for the dsPIC33EP512MU810 microcontroller (Base DD1\DD2) or correct version drivers for vlfx.

**Comment by EIREXE** [comment]
> 
> 
> Hello, i am using vlfx whith FwClubSportBaseUpdater.exe but i see this message "Binary not found in DB".
> 
> Could you send the firmware for the dsPIC33EP512MU810 microcontroller (Base DD1\DD2) or correct version drivers for vlfx.

Can you hop on discord and send me the binary so I can add it to the DB? What driver version are you using?

EIREXE#2836

Cheers.

**Comment by EIREXE** [comment]
Fixed in dd76d8f
